development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: marlon
  password: marlon

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: marlon
  password: marlon

production:
  adapter: postgresql
<<<<<<< HEAD
  database: dbp6heirs9v4qd
  host: "ec2-54-197-253-210.compute-1.amazonaws.com"
  username: ytuzoxyzvdyimk
  password: "b75e0a56812fe83a881aa3ca15a254f8dbb5b2094ac06b4b24ff7546dae9c236"
  port: 5432
=======
  encoding: utf8
  database: project_production
  pool: 5
  username: marlon
  password: marlon

cucumber:
  <<: *TEST
>>>>>>> origin/marlon
